name: Mirroring-Bitbucket

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1
        - uses: spyoungtech/mirror-action@master
          with:
            REMOTE: 'https://ikatheesh@bitbucket.org/kasfy/kasfy.git'
            GIT_USERNAME: ikatheesh
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
